name: S3 Static Website Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get -y update
          sudo apt-get -y install awscli

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://aws-bucket-static-website-example1 --delete --exclude '*.git*' --exclude '*.github*'
