name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
<<<<<<< HEAD
            aws configure set region us-east-1

  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

=======
  aws-region: ap-south-1
>>>>>>> 77f056d91ef6ae94d71d5b10e1fa9461859d9ed5

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

     # - name: Setup Terraform
     #   uses: hashicorp/setup-terraform@v1
      #  with:
                 
#       - name: Configure AWS CLI
#         run: |
#            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
#            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#            aws configure set region us-east-1
#       # Other steps in your workflow...

      - name: Terraform Init
        run: terraform init -backend-config="credentials_token=${{secrets.TF_API_TOKEN}} -debug

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan  -var-file vars.tfvars -out=tfplan

      - name: Terraform Apply
        run: terraform apply  -var-file vars.tfvars -auto-approve tfplan
