name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

  aws-region: ap-south-1
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform Init
        run: terraform init -var-file vars.tfvars

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan  -var-file vars.tfvars -out=tfplan

      - name: Terraform Apply
        run: terraform apply  -var-file vars.tfvars -auto-approve tfplan
